"""add_is_tour_seen_to_user

Revision ID: 180496ed4400
Revises: e53c2bd93fbc
Create Date: 2026-07-10 19:23:10.866402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180496ed4400'
down_revision: Union[str, Sequence[str], None] = 'e53c2bd93fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_tour_seen', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_tour_seen')
    # ### end Alembic commands ###
