"""add invoice_url to invoice

Revision ID: 56b010c54157
Revises: c2b71a5412e6
Create Date: 2026-05-11 22:20:31.493705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b010c54157'
down_revision: Union[str, Sequence[str], None] = 'c2b71a5412e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('invoice_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'invoice_url')
    # ### end Alembic commands ###
