"""Update invoice model

Revision ID: e53c2bd93fbc
Revises: 56b010c54157
Create Date: 2026-05-11 23:27:14.571893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53c2bd93fbc'
down_revision: Union[str, Sequence[str], None] = '56b010c54157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'invoice_url')
    op.alter_column('invoice', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
